# Generated by Django 4.0.4 on 2022-05-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_description_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transmisson',
            new_name='transmission',
        ),
    ]
